query searchName($name: String, $isAdult: Boolean) {
  Page {
    media(search: $name, isAdult: $isAdult, format_in: [TV, TV_SHORT, MOVIE, SPECIAL, OVA, ONA, MUSIC]) {
      id
      title {
        romaji
        english
        native
      }
      coverImage {
        medium
      }
      format
      averageScore
      genres
      siteUrl
    }
  }
}

query seasonal($page: Int, $isAdult: Boolean) {
  Page(page: $page) {
    pageInfo {
      currentPage
      hasNextPage
    }
    media(isAdult: $isAdult, season: SUMMER, seasonYear: 2022, sort: [SCORE_DESC]) {
      id
      title {
        romaji
        english
        native
      }
      coverImage {
        medium
      }
      format
      averageScore
      genres
      siteUrl
    }
  }
}
